//APP
export const RESET_APPSTATE="RESET_APPSTATE";
//Fetch API
export const FETCH_CATCH = "FETCH_CATCH";

//Profile
export const CHANGE_AVARTAR="CHANGE_AVARTAR";
export const CHANGE_AVARTAR_ERROR="CHANGE_AVARTAR_ERROR";

export const REFRESH_TOKEN_FAIL="REFRESH_TOKEN_FAIL";
//authen
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EROR = "LOGIN_EROR";
export const LOGING = "LOGING";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const LOG_OUT_ERROR="LOG_OUT_ERROR";
export const EXPORT_FORM = "EXPORT_FORM";
export const AUTHEN_EXPRI = "AUTHEN_EXPRI";
//change password
//authen
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_EROR = "CHANGE_PASSWORD_EROR";
export const CHANGE_PASSWORDG = "CHANGE_PASSWORDG";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

//Home(App)
export const SIGNALR_DISCONNECT = "SIGNALR_DISCONNECT";
export const SIGNALR_RECONNECTING = "SIGNALR_RECONNECTING";
export const SIGNALR_CONNECTED = "SIGNALR_CONNECTED";

export const DEFAULT = "DEFAULT";
//search actions
export const LIST_RESULT = "LIST_RESULT";
export const SEARCHING = "SEARCHING";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_FETCH_ERROR = "SEARCH_FETCH_ERROR";
export const SEARCH_RESET = "SEARCH_RESET";
export const SEARCH_LOAD_MORE = "SEARCH_LOAD_MORE";
export const SEARCH_CLEAR_ERROR = "SEARCH_CLEAR_ERROR";
//chat actions
export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING'
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS'
export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR'
export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE'
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'